import sys, os.path

def current_file_path():
    if getattr(sys, 'frozen', False):
        # 打包后的可执行文件
        fp = sys.executable
    else:
        # 普通 Python 文件
        fp = os.path.abspath(__file__)
    return os.path.dirname(fp)

DIR_PYTHON = sys.exec_prefix
## folders and icons
DIR_APP = os.path.realpath(os.path.join(current_file_path(), '..'))
DIR_IMG = os.path.join(DIR_APP, 'images')
DIR_DOC = os.path.join(DIR_APP, 'doc')
DIR_CSS = os.path.join(DIR_APP, 'assets', 'css')

## ICONS ------------------------------------------
ICON_APP = os.path.join(DIR_IMG, 'ppmb.png')
ICON_APPEXIT = os.path.join(DIR_IMG, 'exit.png')
ICON_OK = os.path.join(DIR_IMG, 'gtk-ok.png')
ICON_NO = os.path.join(DIR_IMG, 'gtk-no.png')
ICON_BJ = os.path.join(DIR_IMG, 'bibjournal.png')
ICON_BE = os.path.join(DIR_IMG, 'bibebook.png')
ICON_BU = os.path.join(DIR_IMG, 'bibuser.png')
ICON_CONFIG = os.path.join(DIR_IMG, 'config.png')
ICON_CLEAR = os.path.join(DIR_IMG, 'clear.png')
ICON_DBBACKUP = os.path.join(DIR_IMG, 'backup.png')
ICON_DBRESTORE = os.path.join(DIR_IMG, 'restore.png')
ICON_DELETE = os.path.join(DIR_IMG, 'delete.png')
ICON_DESTROY = os.path.join(DIR_IMG, 'destroy.png')
ICON_EDIT = os.path.join(DIR_IMG, 'edit.png')
ICON_EDIT2 = os.path.join(DIR_IMG, 'edit2.png')
ICON_COPY = os.path.join(DIR_IMG, 'copy.png')
ICON_FAVORITE = os.path.join(DIR_IMG, 'favorite.png')
ICON_FILEIMPORT = os.path.join(DIR_IMG, 'import.png')
ICON_FILEEXPORT = os.path.join(DIR_IMG, 'export.png')
ICON_FILTER = os.path.join(DIR_IMG, 'filter.png')
ICON_FORMAT_BOLD = os.path.join(DIR_IMG, 'format-bold.png')
ICON_FORMAT_EMPH = os.path.join(DIR_IMG, 'format-emph.png')
ICON_FORMAT_ITALIC = os.path.join(DIR_IMG, 'format-italic.png')
ICON_FORMAT_CLEAR = os.path.join(DIR_IMG, 'clear.png')
ICON_FORMAT_PLAIN = os.path.join(DIR_IMG, 'format-text-plain.png')
ICON_FORMAT_LIST1 = os.path.join(DIR_IMG, 'format-list-ordered.png')
ICON_FORMAT_LIST2 = os.path.join(DIR_IMG, 'format-list-unordered.png')
ICON_FORMAT_INDENT_MORE = os.path.join(DIR_IMG, 'format-indent-more.png')
ICON_FORMAT_INDENT_LESS = os.path.join(DIR_IMG, 'format-indent-less.png')
ICON_FORMAT_FONT_LARGER = os.path.join(DIR_IMG, 'format-font-larger.png')
ICON_FORMAT_FONT_SMALLER = os.path.join(DIR_IMG, 'format-font-smaller.png')
ICON_FORMAT_COLOR = os.path.join(DIR_IMG, 'color.png')
ICON_COLOR = os.path.join(DIR_IMG, 'color.png')
ICON_FORMAT_H1 = os.path.join(DIR_IMG, 'format-h1.png')
ICON_FORMAT_H2 = os.path.join(DIR_IMG, 'format-h2.png')
ICON_FILE_WORD = os.path.join(DIR_IMG, 'file-word.png')
ICON_FILE_EXCEL = os.path.join(DIR_IMG, 'file-excel.png')
ICON_FILE_PDF = os.path.join(DIR_IMG, 'file-pdf.png')
ICON_FILE_TEX = os.path.join(DIR_IMG, 'file-tex.png')
ICON_FILE_ADD = os.path.join(DIR_IMG, 'file-plus.png')
ICON_FILE_OPEN = os.path.join(DIR_IMG, 'fileopen.png')
ICON_FILE_OPEN2 = os.path.join(DIR_IMG, 'document-open.png')
ICON_FILE_IMPORT = os.path.join(DIR_IMG, 'fileimport.png')
ICON_FILE_EXPORT = os.path.join(DIR_IMG, 'save.png')
ICON_FILE_TEXT = os.path.join(DIR_IMG, 'file-text.png')
ICON_FILE_MD = os.path.join(DIR_IMG, 'markdown.png')
ICON_FOLDER_OPEN = os.path.join(DIR_IMG, 'folder-open.png')
ICON_FOLDER_NEW = os.path.join(DIR_IMG, 'folder-new.png')
ICON_GO_BACK = os.path.join(DIR_IMG, 'go-back-ltr.png')
ICON_GO_FORWARD = os.path.join(DIR_IMG, 'go-back-rtl.png')
ICON_HELP = os.path.join(DIR_IMG, 'help.png')
ICON_INFO = os.path.join(DIR_IMG, 'info1.png')
ICON_ISSN = os.path.join(DIR_IMG, 'issn.png')
ICON_JLIST = os.path.join(DIR_IMG, 'journals.png')
ICON_LOADING = os.path.join(DIR_IMG, 'progress_bar.gif')
ICON_LIST_ADD = os.path.join(DIR_IMG, 'list-add.png')
ICON_PLUS = os.path.join(DIR_IMG, 'list-add.png')
ICON_PAGEUP = os.path.join(DIR_IMG, 'go-up.png')
ICON_PAGEDOWN = os.path.join(DIR_IMG, 'go-down.png')
ICON_MINUS = os.path.join(DIR_IMG, 'list-minus.png')
ICON_MAXIMIZE = os.path.join(DIR_IMG, 'maximize.png')
ICON_MINIMIZE = os.path.join(DIR_IMG, 'minimize.png')
## AUDIO/MEDIA
ICON_AUDIO_PLAY = os.path.join(DIR_IMG, 'audio-play.png')
ICON_AUDIO_STOP = os.path.join(DIR_IMG, 'audio-stop.png')
ICON_AUDIO_DEL = os.path.join(DIR_IMG, 'audio-delete.png')
ICON_MEDIA_PLAY = os.path.join(DIR_IMG, 'media-play1.png')
ICON_MEDIA_PAUSE = os.path.join(DIR_IMG, 'media-pause.png')
ICON_MEDIA_NEXT = os.path.join(DIR_IMG, 'media-next.png')
ICON_MEDIA_PREV = os.path.join(DIR_IMG, 'media-prev.png')
ICON_NEXT = os.path.join(DIR_IMG, 'next.png')
ICON_PREV = os.path.join(DIR_IMG, 'prev.png')
ICON_PUBMED = os.path.join(DIR_IMG, 'pubmed.png')
ICON_RENAME = os.path.join(DIR_IMG, 'rename.png')
ICON_REFRESH = os.path.join(DIR_IMG, 'refresh.png')
ICON_SPRINGER = os.path.join(DIR_IMG, 'springer.png')
ICON_SEARCH = os.path.join(DIR_IMG, 'search.png')
ICON_SEARCH_WEB = os.path.join(DIR_IMG, 'websearch.png')
ICON_SORT = os.path.join(DIR_IMG, 'sort.png')
ICON_SAVE = os.path.join(DIR_IMG, 'save.png')
ICON_SAVE2 = os.path.join(DIR_IMG, 'media-floppy.png')
ICON_SAVEAS = os.path.join(DIR_IMG, 'saveas.png')
ICON_SAVE_IMPORT = os.path.join(DIR_IMG, 'save-import.png')
ICON_SAVE_PLUS = os.path.join(DIR_IMG, 'save-plus.png')
ICON_OPEN = os.path.join(DIR_IMG, 'document-open.png')
ICON_SWITCHVIEW = os.path.join(DIR_IMG, 'switchview.png')
ICON_UPDATE = os.path.join(DIR_IMG, 'update.png')
ICON_VIEWALL = os.path.join(DIR_IMG, 'viewall.png')
ICON_VIEW_FULLSCREEN = os.path.join(DIR_IMG, 'view-fullscreen.svg')
ICON_VIEW_RESTORE = os.path.join(DIR_IMG, 'view-restore.svg')
ICON_VIEWCODE= os.path.join(DIR_IMG, 'viewcode.png')
ICON_VIEWDETAIL = os.path.join(DIR_IMG, 'viewdetail.png')
ICON_VIEWDOC = os.path.join(DIR_IMG, 'viewdoc.png')
ICON_VIEWHTML = os.path.join(DIR_IMG, 'viewhtml.png')
ICON_VIEWLIST = os.path.join(DIR_IMG, 'list.png')
ICON_WC = os.path.join(DIR_IMG, 'wc.png')
ICON_VIPSENTENCE = os.path.join(DIR_IMG, 'writing.png')
